# Generated by Django 5.1.2 on 2024-10-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0004_alter_invoice_invoice_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='line_eight',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Line 8'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_eight_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_eight_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_eight_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_nine',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Line 9'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_nine_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_nine_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_nine_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_seven',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Line 7'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_seven_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_seven_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_seven_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_six',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Line 6'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_six_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_six_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_six_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_ten',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Line 10'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_ten_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_ten_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_ten_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('Invoice', 'Invoice'), ('Receipt', 'Receipt')], default='Invoice', max_length=50, null=True),
        ),
    ]
