# Generated by Django 5.1.2 on 2024-10-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0008_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('Invoice', 'Invoice'), ('Receipt', 'Receipt')], default='Invoice', max_length=50, null=True),
        ),
    ]
